## PART 3

#### To make analysis of data in table easier, we can reshape the data into a more computer-friendly form using Pandas in Python. Pandas.melt() is one of the function to do so..
Pandas.melt() unpivots a DataFrame from wide format to long format.
melt() function is useful to message a DataFrame into a format where one or more columns are identifier variables, while all other columns, considered measured variables, are unpivoted to the row axis, leaving just two non-identifier columns, variable and value.
Syntax :

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("/Users/aryansaini/Documents/Virtual Environment/Python/Pandas/Part 3/weather.csv")
df

         day  chicago  chennai  berlin
0     Monday       32       75      41
1    Tuesday       30       77      43
2  Wednesday       28       75      45
3   Thursday       22       82      38
4     Friday       30       83      30
5   Saturday       20       81      45
6     Sunday       25       77      47

In [6]:
#Using melt to transform the data frame

df1 = pd.melt(df, id_vars=['day'])
df1[df1['variable']=='chennai']

          day variable  value
7      Monday  chennai     75
8     Tuesday  chennai     77
9   Wednesday  chennai     75
10   Thursday  chennai     82
11     Friday  chennai     83
12   Saturday  chennai     81
13     Sunday  chennai     77

In [7]:
df1 = pd.melt(df, id_vars=['day'], var_name='city', value_name='temperature')
df1

          day     city  temperature
0      Monday  chicago           32
1     Tuesday  chicago           30
2   Wednesday  chicago           28
3    Thursday  chicago           22
4      Friday  chicago           30
5    Saturday  chicago           20
6      Sunday  chicago           25
7      Monday  chennai           75
8     Tuesday  chennai           77
9   Wednesday  chennai           75
10   Thursday  chennai           82
11     Friday  chennai           83
12   Saturday  chennai           81
13     Sunday  chennai           77
14     Monday   berlin           41
15    Tuesday   berlin           43
16  Wednesday   berlin           45
17   Thursday   berlin           38
18     Friday   berlin           30
19   Saturday   berlin           45
20     Sunday   berlin           47

## Video 12

In [8]:
#Stacking, unstacking

In [21]:
df = pd.read_excel("/Users/aryansaini/Documents/Virtual Environment/Python/Pandas/Part 3/stocks.xlsx", header=[0,1])
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

In [26]:
df_stacked = df.stack(level=0, dropna=True)
df_stacked

                                   Company  Facebook  Google  Microsoft
0 Price                                NaT    155.00   955.0      66.00
  Price to earnings ratio (P/E)        NaT     37.10    32.0      30.31
  Unnamed: 0_level_0            2017-06-05       NaN     NaN        NaN
1 Price                                NaT    150.00   987.0      69.00
  Price to earnings ratio (P/E)        NaT     36.98    31.3      30.56
  Unnamed: 0_level_0            2017-06-06       NaN     NaN        NaN
2 Price                                NaT    153.00   963.0      62.00
  Price to earnings ratio (P/E)        NaT     36.78    31.7      30.46
  Unnamed: 0_level_0            2017-06-07       NaN     NaN        NaN
3 Price                                NaT    155.00  1000.0      61.00
  Price to earnings ratio (P/E)        NaT     36.11    31.2      30.11
  Unnamed: 0_level_0            2017-06-08       NaN     NaN        NaN
4 Price                                NaT    156.00  1012.0      66.00
  Price to earnings ratio (P/E)        NaT     37.07    30.0      31.00
  Unnamed: 0_level_0            2017-06-09       NaN     NaN        NaN

In [29]:
df_stacked= df_stacked.unstack(level=0)
df_stacked

                                             Company Facebook  Google  \
Price                         0                  NaT    155.0   955.0
                              1                  NaT    150.0   987.0
                              2                  NaT    153.0   963.0
                              3                  NaT    155.0  1000.0
                              4                  NaT    156.0  1012.0
Price to earnings ratio (P/E) 0                  NaT     37.1    32.0
                              1                  NaT    36.98    31.3
                              2                  NaT    36.78    31.7
                              3                  NaT    36.11    31.2
                              4                  NaT    37.07    30.0
Unnamed: 0_level_0            0  2017-06-05 00:00:00      NaN     NaN
                              1  2017-06-06 00:00:00      NaN     NaN
                              2  2017-06-07 00:00:00      NaN     NaN
                              3  2017-06-08 00:00:00      NaN     NaN
                              4  2017-06-09 00:00:00      NaN     NaN

                                Microsoft
Price                         0      66.0
                              1      69.0
                              2      62.0
                              3      61.0
                              4      66.0
Price to earnings ratio (P/E) 0     30.31
                              1     30.56
                              2     30.46
                              3     30.11
                              4      31.0
Unnamed: 0_level_0            0       NaN
                              1       NaN
                              2       NaN
                              3       NaN
                              4       NaN

In [30]:
#Importing a new data frame
df = pd.read_excel("/Users/aryansaini/Documents/Virtual Environment/Python/Pandas/Part 3/stocks_3_levels.xlsx", header=[0,1,2])
df

  Unnamed: 0_level_0 Price Ratios                   \
  Unnamed: 0_level_1        Price
             Company     Facebook Google Microsoft
0            Q1 2016          155    955        66
1            Q2 2016          150    987        69
2            Q3 2016          153    963        62
3            Q4 2016          155   1000        61
4            Q1 2017          156   1012        66

                                                 Income Statement         \
  Price to earnings ratio (P/E)                         Net Sales
                       Facebook Google Microsoft         Facebook Google
0                         37.10   32.0     30.31              2.6     20
1                         36.98   31.3     30.56              3.1     22
2                         36.78   31.7     30.46              4.3     24
3                         36.11   31.2     30.11              6.7     26
4                         37.07   30.0     31.00              8.1     31


            Net Profit
  Microsoft   Facebook Google Microsoft
0     18.70       0.80   5.43      4.56
1     21.30       0.97   5.89      5.10
2     21.45       1.20   6.10      5.43
3     21.88       1.67   6.50      5.89
4     22.34       2.03   6.40      6.09

In [33]:
df.stack(level=2)

            Income Statement           Price Ratios  \
                  Net Profit Net Sales        Price
0 Company                NaN       NaN          NaN
  Facebook              0.80      2.60        155.0
  Google                5.43     20.00        955.0
  Microsoft             4.56     18.70         66.0
1 Company                NaN       NaN          NaN
  Facebook              0.97      3.10        150.0
  Google                5.89     22.00        987.0
  Microsoft             5.10     21.30         69.0
2 Company                NaN       NaN          NaN
  Facebook              1.20      4.30        153.0
  Google                6.10     24.00        963.0
  Microsoft             5.43     21.45         62.0
3 Company                NaN       NaN          NaN
  Facebook              1.67      6.70        155.0
  Google                6.50     26.00       1000.0
  Microsoft             5.89     21.88         61.0
4 Company                NaN       NaN          NaN
  Facebook              2.03      8.10        156.0
  Google                6.40     31.00       1012.0
  Microsoft             6.09     22.34         66.0

                                          Unnamed: 0_level_0
            Price to earnings ratio (P/E) Unnamed: 0_level_1
0 Company                             NaN            Q1 2016
  Facebook                          37.10                NaN
  Google                            32.00                NaN
  Microsoft                         30.31                NaN
1 Company                             NaN            Q2 2016
  Facebook                          36.98                NaN
  Google                            31.30                NaN
  Microsoft                         30.56                NaN
2 Company                             NaN            Q3 2016
  Facebook                          36.78                NaN
  Google                            31.70                NaN
  Microsoft                         30.46                NaN
3 Company                             NaN            Q4 2016
  Facebook                          36.11                NaN
  Google                            31.20                NaN
  Microsoft                         30.11                NaN
4 Company                             NaN            Q1 2017
  Facebook                          37.07                NaN
  Google                            30.00                NaN
  Microsoft                         31.00                NaN

## Video 13

## Contingency table / Cross Tabs
### Crosstab (also known as contingency table or cross tabulation)
### is a table showing frequency distribution of one variable in 
### rows and another on columns. pandas crosstab method can be used 
### to generate these contingency tables that are extremely useful in survey and business analytics.

In [38]:
df = pd.read_excel("/Users/aryansaini/Documents/Virtual Environment/Python/Pandas/Part 3/survey.xls")
df

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima   Bangadesh  Female   31       Left
5    Kadir   Bangadesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

In [41]:
pd.crosstab(df.Sex, df.Age)

Age     18  19  22  23  25  31  35  37  43  52  58
Sex
Female   1   0   0   1   0   1   0   0   0   1   1
Male     0   1   1   0   1   1   1   1   1   0   0

In [44]:
#We can call the margin arguement to view the total 
pd.crosstab(df.Nationality, df.Handedness, margins=True)

Handedness   Left  Right  All
Nationality
Bangadesh       2      0    2
China           2      1    3
India           2      1    3
USA             1      3    4
All             7      5   12

In [52]:
#If we want to have multiple columns 
pd.crosstab([df.Nationality,df.Sex, df.Age], df.Handedness ,normalize=True)

Handedness                  Left     Right
Nationality Sex    Age
Bangadesh   Female 31   0.083333  0.000000
            Male   25   0.083333  0.000000
China       Female 52   0.000000  0.083333
                   58   0.083333  0.000000
            Male   43   0.083333  0.000000
India       Male   31   0.083333  0.000000
                   35   0.083333  0.000000
                   37   0.000000  0.083333
USA         Female 18   0.000000  0.083333
                   23   0.000000  0.083333
            Male   19   0.000000  0.083333
                   22   0.083333  0.000000

In [55]:
pd.crosstab(df.Nationality, df.Handedness, normalize='index')

Handedness       Left     Right
Nationality
Bangadesh    1.000000  0.000000
China        0.666667  0.333333
India        0.666667  0.333333
USA          0.250000  0.750000

In [57]:
pd.crosstab(df.Sex, df.Handedness)

Handedness  Left  Right
Sex
Female         2      3
Male           5      2

In [60]:
#Suppose now we want to find out the average age of male or females based on the contigency table
import numpy as np
pd.crosstab(df.Sex, df.Handedness, values=df.Age, aggfunc= np.average)

Handedness  Left  Right
Sex
Female      44.5   31.0
Male        31.2   28.0

## Video 14

In [62]:
#Today we will read SQL data into pandas dataframe and back

In [64]:
pip install PyMySQL

Collecting PyMySQL
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 550 kB/s
Installing collected packages: PyMySQL
Successfully installed PyMySQL-1.0.2
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [65]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading SQLAlchemy-1.4.32.tar.gz (8.1 MB)
     |████████████████████████████████| 8.1 MB 1.8 MB/s
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for sqlalchemy, since package 'wheel' is not installed.
Installing collected packages: sqlalchemy
    Running setup.py install for sqlalchemy ... done
Successfully installed sqlalchemy-1.4.32
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [72]:
import sqlalchemy

In [73]:
#Creating an engine to connect to the postgresql database
engine =sqlalchemy.create_engine('postgresql://postgres:1234/University_Database')

ModuleNotFoundError: No module named 'psycopg2'

In [77]:
pip install psycopg2-binary

Collecting psycopg2-binary
  Using cached psycopg2-binary-2.9.3.tar.gz (380 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_448c93206ef14450a6e4761b89dcfb9a/setup.py'"'"'; __file__='"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_448c93206ef14450a6e4761b89dcfb9a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-lh6dp_jo
       cwd: /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_448c93206ef14450a6e4761b89dcfb9a/
  Complete output (20 lines):
  running egg_info
  creating /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-lh6dp_jo/psycopg2_binary.egg-info
  writing manifest file '/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-lh6dp_jo/psycopg2_binary.egg-info/SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d7/1c/8d042630c5ff3c3e6d93c992bd7ecf516d577803b96781c6caa649bbf6e5/psycopg2-binary-2.9.3.tar.gz#sha256=761df5313dc15da1502b21453642d7599d26be88bff659382f8f9747c7ebea4e (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-binary-2.9.2.tar.gz (380 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_f87f1950fa4144cd8d0ae5eaddcb130b/setup.py'"'"'; __file__='"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_f87f1950fa4144cd8d0ae5eaddcb130b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-sttvx2n8
       cwd: /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_f87f1950fa4144cd8d0ae5eaddcb130b/
  Complete output (20 lines):
  running egg_info
  creating /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-sttvx2n8/psycopg2_binary.egg-info
  writing manifest file '/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-sttvx2n8/psycopg2_binary.egg-info/SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d1/6d/bdb09cc1ccc6aa5e611c4d74daf751f8881ae231933f4ef1d4f6d699d021/psycopg2-binary-2.9.2.tar.gz#sha256=234b1f48488b2f86aac04fb00cb04e5e9bcb960f34fa8a8e41b73149d581a93b (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-binary-2.9.1.tar.gz (380 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_0bc6c8e88a3e4f1abcba9ade2960d321/setup.py'"'"'; __file__='"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_0bc6c8e88a3e4f1abcba9ade2960d321/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-1ms6pics
       cwd: /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_0bc6c8e88a3e4f1abcba9ade2960d321/
  Complete output (20 lines):
  running egg_info
  creating /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-1ms6pics/psycopg2_binary.egg-info
  writing manifest file '/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-1ms6pics/psycopg2_binary.egg-info/SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/14/65/223a5b4146b1d5d5ab66f16ef194916a1ed9720da1f118d7bfb60b8f2bea/psycopg2-binary-2.9.1.tar.gz#sha256=b0221ca5a9837e040ebf61f48899926b5783668b7807419e4adae8175a31f773 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-binary-2.9.tar.gz (379 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_376a1c23ef794c4195151a6014d2746d/setup.py'"'"'; __file__='"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_376a1c23ef794c4195151a6014d2746d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-gv1jvuio
       cwd: /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_376a1c23ef794c4195151a6014d2746d/
  Complete output (20 lines):
  running egg_info
  creating /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-gv1jvuio/psycopg2_binary.egg-info
  writing manifest file '/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-gv1jvuio/psycopg2_binary.egg-info/SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/39/55/54778407e306de1acd3c616dc6a04e3821effa52c21d6c688d4947878658/psycopg2-binary-2.9.tar.gz#sha256=5515c626df6ce6e9058883ace33fece4e32d3409eb70367cc62952f6d6a50dee (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-binary-2.8.6.tar.gz (384 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_2c0ab0483deb4233aff9fb01b0f2012d/setup.py'"'"'; __file__='"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_2c0ab0483deb4233aff9fb01b0f2012d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-l4w_pja8
       cwd: /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_2c0ab0483deb4233aff9fb01b0f2012d/
  Complete output (20 lines):
  running egg_info
  creating /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-l4w_pja8/psycopg2_binary.egg-info
  writing manifest file '/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-l4w_pja8/psycopg2_binary.egg-info/SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/fc/51/0f2c6aec5c59e5640f507b59567f63b9d73a9317898810b4db311da32dfc/psycopg2-binary-2.8.6.tar.gz#sha256=11b9c0ebce097180129e422379b824ae21c8f2a6596b159c7659e2e5a00e1aa0 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-binary-2.8.5.tar.gz (381 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_3772c8c64259427a9b4282fc43d143fe/setup.py'"'"'; __file__='"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_3772c8c64259427a9b4282fc43d143fe/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-pil7h_md
       cwd: /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_3772c8c64259427a9b4282fc43d143fe/
  Complete output (20 lines):
  running egg_info
  creating /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-pil7h_md/psycopg2_binary.egg-info
  writing manifest file '/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-pil7h_md/psycopg2_binary.egg-info/SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/97/00/ed4c82364741031d745867f83820d4f373aa891098a5785841850491c9ba/psycopg2-binary-2.8.5.tar.gz#sha256=ccdc6a87f32b491129ada4b87a43b1895cf2c20fdb7f98ad979647506ffc41b6 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-binary-2.8.4.tar.gz (378 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_7f8d8e4044254c5c9ab8071ef98213ce/setup.py'"'"'; __file__='"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_7f8d8e4044254c5c9ab8071ef98213ce/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-_vh3wy91
       cwd: /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_7f8d8e4044254c5c9ab8071ef98213ce/
  Complete output (20 lines):
  running egg_info
  creating /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-_vh3wy91/psycopg2_binary.egg-info
  writing manifest file '/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-_vh3wy91/psycopg2_binary.egg-info/SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <http://initd.org/psycopg/docs/install.html>).

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/00/7b/a623f49b3248957e7eaaac52eba1117209775d54e7a8501c460473a7ba4f/psycopg2-binary-2.8.4.tar.gz#sha256=3a2522b1d9178575acee4adf8fd9f979f9c0449b00b4164bb63c3475ea6528ed (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-binary-2.8.3.tar.gz (378 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '/Users/aryansaini/Documents/Virtual Environment/common_venv/bin/python3.9' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_6e63ce8b87854b13b4949c27fe051845/setup.py'"'"'; __file__='"'"'/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_6e63ce8b87854b13b4949c27fe051845/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-sp90yp73
       cwd: /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-install-8z_r4vz7/psycopg2-binary_6e63ce8b87854b13b4949c27fe051845/
  Complete output (20 lines):
  running egg_info
  creating /private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-sp90yp73/psycopg2_binary.egg-info
  writing manifest file '/private/var/folders/48/l14403_9457144q4v0_bsdzh0000gn/T/pip-pip-egg-info-sp90yp73/psycopg2_binary.egg-info/SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <http://initd.org/psycopg/docs/install.html>).

  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/80/91/91911be01869fa877135946f928ed0004e62044bdd876c1e0f12e1b5fb90/psycopg2-binary-2.8.3.tar.gz#sha256=cd37cc170678a4609becb26b53a2bc1edea65177be70c48dd7b39a1149cabd6e (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-binary-2.8.2.tar.gz (369 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1: